version: 2
jobs:
  build:
    machine:
      image: circleci/classic

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose up -d
            # docker-compose will start 2 containers, the one with service will be named `contacts`
            # we start another container with curl in the same network as `contacts`, this way we have
            # all exposed ports from `contacts` available on `localhost` in this new container
            appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:8080/api